In [1]:
import pandas as pd
import os
import psycopg2
import warnings
warnings.filterwarnings('ignore')

trend_path = r"C:\Users\Administrator\Desktop\data_learn\Hot-Drink-Retail-Analysis\data\processed\simulated_trend_1year.csv"
weather_path = r"C:\Users\Administrator\Desktop\data_learn\Hot-Drink-Retail-Analysis\data\raw\beijing_weather.csv"

trend_df = pd.read_csv(trend_path)
weather_df = pd.read_csv(weather_path)

display(trend_df.head(3))
display(weather_df.head(3))

        date  coffee_index  milktea_index
0  2025/2/26           581            572
1  2025/2/27           598            537
2  2025/2/28           592            524

        time  tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
0  2025/2/28   9.6  -2.1  19.1   0.0   NaN    77   6.0   NaN  1014.3   NaN
1   2025/3/1   9.7   2.1  19.1   0.0   NaN    78   7.8   NaN  1013.9   NaN
2   2025/3/2   2.7  -1.9  15.6   0.8   NaN   103   7.5   NaN  1024.7   NaN

In [ ]:
trend_df['date'] = pd.to_datetime(trend_df['date'])
weather_df['time'] = pd.to_datetime(weather_df['time'])

merge_df = pd.merge(
    left=trend_df,
    right=weather_df,
    left_on='date',
    right_on='time',
    how='inner'
)

display(merge_df.head())

print(f'趋势表的行数: {len(trend_df)}')
print(f'天气表的行数: {len(weather_df)}')
print(f'合并后表的行数: {len(merge_df)}')

In [7]:
conn = psycopg2.connect(
    host = 'localhost',
    port = '5432',
    database = 'postgres',
    user = 'postgres',
    password = ''
)

query ="""
SELECT 
    t.*,
    w.tavg,
    w.tmin,
    w.tmax
FROM hot_drink_retail.simulated_trend_1year AS t
INNER JOIN hot_drink_retail.beijing_weather AS w
ON t.date::DATE = w.time::DATE
"""

df_sql = pd.read_sql_query(query, conn)
display(df_sql.head())

        date  coffee_index  milktea_index  tavg  tmin  tmax
0  2025/2/28           592            524   9.6  -2.1  19.1
1   2025/3/1           446            768   9.7   2.1  19.1
2   2025/3/2           443            740   2.7  -1.9  15.6
3   2025/3/3           557            557   5.0  -3.2   9.2
4   2025/3/4           589            593   4.4   1.8  10.1